config/routes.rb
Rugby2::Application.routes.draw do
  resources :siaikekkas

end

app/models/siaikekka.rb
class Siaikekka < ActiveRecord::Base
end

app/controllers/application_controller.rb
# coding: utf-8

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/siaikekkas_controller.rb
# coding: utf-8

class SiaikekkasController < ApplicationController
  # GET /siaikekkas
  # GET /siaikekkas.xml
  def index
    @siaikekkas = Siaikekka.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @siaikekkas }
    end
  end

  # GET /siaikekkas/1
  # GET /siaikekkas/1.xml
  def show
    @siaikekka = Siaikekka.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @siaikekka }
    end
  end

  # GET /siaikekkas/new
  # GET /siaikekkas/new.xml
  def new
    @siaikekka = Siaikekka.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @siaikekka }
    end
  end

  # GET /siaikekkas/1/edit
  def edit
    @siaikekka = Siaikekka.find(params[:id])
  end

  # POST /siaikekkas
  # POST /siaikekkas.xml
  def create
    @siaikekka = Siaikekka.new(params[:siaikekka])

    respond_to do |format|
      if @siaikekka.save
        format.html { redirect_to(@siaikekka, :notice => 'Siaikekka was successfully created.') }
        format.xml  { render :xml => @siaikekka, :status => :created, :location => @siaikekka }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @siaikekka.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /siaikekkas/1
  # PUT /siaikekkas/1.xml
  def update
    @siaikekka = Siaikekka.find(params[:id])

    respond_to do |format|
      if @siaikekka.update_attributes(params[:siaikekka])
        format.html { redirect_to(@siaikekka, :notice => 'Siaikekka was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @siaikekka.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /siaikekkas/1
  # DELETE /siaikekkas/1.xml
  def destroy
    @siaikekka = Siaikekka.find(params[:id])
    @siaikekka.destroy

    respond_to do |format|
      format.html { redirect_to(siaikekkas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/siaikekkas_helper.rb
module SiaikekkasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rugby2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/siaikekkas/_form.html.erb
<%= form_for(@siaikekka) do |f| %>
  <% if @siaikekka.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@siaikekka.errors.count, "error") %> prohibited this siaikekka from being saved:</h2>

      <ul>
      <% @siaikekka.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :taikaimei %><br />
    <%= f.text_field :taikaimei %>
  </div>
  <div class="field">
    <%= f.label :hiduke %><br />
    <%= f.text_field :hiduke %>
  </div>
  <div class="field">
    <%= f.label :taisenaite %><br />
    <%= f.text_field :taisenaite %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :grand %><br />
    <%= f.text_field :grand %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/siaikekkas/edit.html.erb
<h1>Editing siaikekka</h1>

<%= render 'form' %>

<%= link_to 'Show', @siaikekka %> |
<%= link_to 'Back', siaikekkas_path %>

app/views/siaikekkas/index.html.erb
# coding: utf-8
<h1>試合結果一覧</h1>

<table>
  <tr>
    <th>大会</th>
    <th>日付</th>
    <th>対戦カード</th>
    <th>最終スコア</th>
    <th>グランド</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @siaikekkas.each do |siaikekka| %>
  <tr>
    <td><%= siaikekka.taikaimei %></td>
    <td><%= siaikekka.hiduke %></td>
    <td><%= siaikekka.taisenaite %></td>
    <td><%= siaikekka.score %></td>
    <td><%= siaikekka.grand %></td>
    <td><%= link_to 'Show', siaikekka %></td>
    <td><%= link_to 'Edit', edit_siaikekka_path(siaikekka) %></td>
    <td><%= link_to 'Destroy', siaikekka, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Siaikekka', new_siaikekka_path %>

app/views/siaikekkas/new.html.erb
<h1>New siaikekka</h1>

<%= render 'form' %>

<%= link_to 'Back', siaikekkas_path %>

app/views/siaikekkas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Taikaimei:</b>
  <%= @siaikekka.taikaimei %>
</p>

<p>
  <b>Hiduke:</b>
  <%= @siaikekka.hiduke %>
</p>

<p>
  <b>Taisenaite:</b>
  <%= @siaikekka.taisenaite %>
</p>

<p>
  <b>Score:</b>
  <%= @siaikekka.score %>
</p>

<p>
  <b>Grand:</b>
  <%= @siaikekka.grand %>
</p>


<%= link_to 'Edit', edit_siaikekka_path(@siaikekka) %> |
<%= link_to 'Back', siaikekkas_path %>